# Data Understanding

| Column Name | Description |
| :--- | :--- |
| **transaction_id** | Unique identifier assigned to each transaction. |
| **transaction_amount** | The monetary value or amount of the transaction. |
| **login_attempts** | Number of login attempts made prior to or during the session. |
| **device_risk_score** | Quantified risk score associated with the user's device. |
| **transfer_frequency** | Frequency of money transfers made by the account. |
| **anomaly_score** | Calculated score indicating how anomalous or unusual the transaction pattern is. |
| **account_age_days** | The age of the bank account measured in days. |
| **transaction_time_hour** | Hour of the day when the transaction occurred (0 to 23 format). |
| **failed_transactions_last_30d** | Number of failed transactions recorded in the past 30 days. |
| **avg_monthly_balance** | Average monthly balance maintained in the account. |
| **daily_transaction_count** | Total number of transactions performed on that specific day. |
| **geo_distance_km** | Geographic distance in kilometers from the user's usual location or previous transaction. |
| **session_duration_minutes** | Total duration of the user's active session in minutes. |
| **transaction_velocity_score** | Score measuring the speed and frequency of transactions over a short window. |
| **payment_channel** | The channel used for the payment (e.g., POS Terminal, Web Banking, ATM, Mobile App). |
| **authentication_type** | The authentication method used for verification (e.g., OTP, Biometric). |
| **card_present_flag** | Binary flag: `1` if the physical card was present, `0` otherwise. |
| **international_transaction_flag** | Binary flag: `1` if it is an international transaction, `0` if domestic. |
| **suspicious_ip_flag** | Binary flag: `1` if the transaction originated from a flagged/suspicious IP address, `0` otherwise. |
| **fraud_flag** | Target label: `True` if the transaction is fraudulent, `False` if legitimate. |

In [245]:
import numpy as np
import pandas as pd
import plotly.express as px

# Data Exploration

In [246]:

df = pd.read_csv('banking_transactions - Copy.csv')
df

,transaction_id,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag
0,1000001,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,63,3189,92,71.8,POS Terminal,OTP,1,1,1,False
1,1000002,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,83,839,63,11.8,Web Banking,Biometric,0,0,1,False
2,1000003,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,9,3938,80,35.7,ATM,OTP,1,0,1,False
3,1000004,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,78,11111,11,74.8,Mobile App,OTP,1,1,0,False
4,1000005,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,17,3171,87,0.0,Mobile App,OTP,1,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,1009996,3552.9,1,36.6,21,0.16,1315,21,12,17919.66,117,14829,36,75.4,Mobile App,Password Only,0,0,1,False
9997,1009997,21559.69,11,14.4,28,0.26,4644,22,11,8477.85,15,10795,63,10.8,POS Terminal,Two-Factor Authentication,0,1,1,False
9998,1009998,4181.33,1,84.0,50,0.23,262,3,3,272564.27,60,3840,91,93.3,Mobile App,Biometric,0,1,1,False
9999,1009999,21443.71,3,33.8,44,0.01,255,4,14,142791.28,116,10110,42,87.1,Mobile App,OTP,1,1,1,False
10000,1010000,24974.25,12,0.0,4,0.87,532,1,19,367234.24,104,7202,102,14.9,POS Terminal,Biometric,0,1,1,True

In [247]:
# Check data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   transaction_id                  10001 non-null  int64
 1   transaction_amount              10001 non-null  object
 2   login_attempts                  10001 non-null  int64
 3   device_risk_score               9969 non-null   float64
 4   transfer_frequency              10001 non-null  int64
 5   anomaly_score                   10001 non-null  float64
 6   account_age_days                10001 non-null  int64
 7   transaction_time_hour           10001 non-null  int64
 8   failed_transactions_last_30d    10001 non-null  int64
 9   avg_monthly_balance             10001 non-null  float64
 10  daily_transaction_count         10001 non-null  int64
 11  geo_distance_km                 10001 non-null  int64
 12  session_duration_minutes        10001 non-null  int64
 13  transaction_velocity_score      10001 non-null  float64
 14  payment_channel                 10001 non-null  object
 15  authentication_type             10001 non-null  object
 16  card_present_flag               10001 non-null  int64
 17  international_transaction_flag  10001 non-null  int64
 18  suspicious_ip_flag              10001 non-null  int64
 19  fraud_flag                      10001 non-null  bool
dtypes: bool(1), float64(4), int64(12), object(3)
memory usage: 1.5+ MB

##transaction_amount needs to convert from object type to float type

In [248]:
# Check duplicates

df.duplicated().sum()

np.int64(1)

In [249]:
df[df.duplicated()]

,transaction_id,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag
4348,1004348,10310.16,6,82.9,53,0.01,2538,13,2,168781.04,116,14564,31,8.9,Web Banking,Password Only,0,1,0,False

In [250]:
# Check misssing values

df.isna().sum()

transaction_id                     0
transaction_amount                 0
login_attempts                     0
device_risk_score                 32
transfer_frequency                 0
anomaly_score                      0
account_age_days                   0
transaction_time_hour              0
failed_transactions_last_30d       0
avg_monthly_balance                0
daily_transaction_count            0
geo_distance_km                    0
session_duration_minutes           0
transaction_velocity_score         0
payment_channel                    0
authentication_type                0
card_present_flag                  0
international_transaction_flag     0
suspicious_ip_flag                 0
fraud_flag                         0
dtype: int64

In [251]:
# Check missing values by percentage
df.isna().mean().round(4)* 100

transaction_id                    0.00
transaction_amount                0.00
login_attempts                    0.00
device_risk_score                 0.32
transfer_frequency                0.00
anomaly_score                     0.00
account_age_days                  0.00
transaction_time_hour             0.00
failed_transactions_last_30d      0.00
avg_monthly_balance               0.00
daily_transaction_count           0.00
geo_distance_km                   0.00
session_duration_minutes          0.00
transaction_velocity_score        0.00
payment_channel                   0.00
authentication_type               0.00
card_present_flag                 0.00
international_transaction_flag    0.00
suspicious_ip_flag                0.00
fraud_flag                        0.00
dtype: float64

In [252]:
# Check summary statistics for Numerical columns

df.describe().round(2)

,transaction_id,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,card_present_flag,international_transaction_flag,suspicious_ip_flag
count,10001.00,10001.00,9969.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.00,10001.0,10001.0
mean,1005000.43,6.44,50.42,39.65,0.35,2510.24,11.55,12.44,249359.47,60.62,7605.26,60.48,50.12,0.49,0.5,0.5
std,2886.76,3.45,29.32,23.42,0.24,1436.26,6.96,7.53,144575.02,34.82,4331.07,34.83,29.27,0.50,0.5,0.5
min,1000001.00,1.00,0.00,0.00,0.01,6.00,0.00,0.00,104.16,1.00,0.00,1.00,0.00,0.00,0.0,0.0
25%,1002501.00,3.00,25.40,19.00,0.17,1272.00,6.00,6.00,122302.26,31.00,3896.00,30.00,24.80,0.00,0.0,0.0
50%,1005000.00,6.00,50.30,40.00,0.31,2511.00,11.00,13.00,249796.21,60.00,7646.00,61.00,50.10,0.00,0.0,1.0
75%,1007500.00,9.00,75.60,60.00,0.48,3746.00,18.00,19.00,373142.99,91.00,11377.00,91.00,75.40,1.00,1.0,1.0
max,1010000.00,12.00,100.00,80.00,0.99,5000.00,23.00,25.00,499968.25,120.00,14997.00,120.00,100.00,1.00,1.0,1.0

In [253]:
# Check summary statistics for Categorical columns

df.describe(include= ['object'])

       transaction_amount payment_channel authentication_type
count               10001           10001               10001
unique               9981               4                   4
top               5203.64      Mobile App                 OTP
freq                    2            4804                4214

# Data Cleaning

- In depth check for categorical columns

In [254]:
# Select all columns with categorical (text/object) data types from the DataFrame
cat_columns = df.select_dtypes(include= ['object']).columns
cat_columns

Index(['transaction_amount', 'payment_channel', 'authentication_type'], dtype='object')

In [255]:
# Loop through each categorical column to check its unique values and their count
for col in cat_columns:
    print(col)
    print(df[col].unique())
    print(df[col].nunique())
    print('-' * 100)

transaction_amount
['17829.01' '16401.83' '9678.29' ... '4181.33' '21443.71' '24974.25']
9981
----------------------------------------------------------------------------------------------------
payment_channel
['POS Terminal' 'Web Banking' 'ATM' 'Mobile App']
4
----------------------------------------------------------------------------------------------------
authentication_type
['OTP' 'Biometric' 'Two-Factor Authentication' 'Password Only']
4
----------------------------------------------------------------------------------------------------

In [256]:
# 1. Convert the column 'transaction_amount' to numeric values.
# Any valid number will be converted, and invalid will automatically turn into NaN instead of crashing.

converted_to_numeric = pd.to_numeric(
    df["transaction_amount"].astype(str).str.strip(), errors="coerce")

# 2. Find and select the rows where the conversion failed (turned into NaN)
error_rows = df[converted_to_numeric.isna()]

# 3. Display these rows to inspect the invalid values
print("Rows containing non-numeric values (errors):")
print(error_rows[["transaction_amount"]])

Rows containing non-numeric values (errors):
     transaction_amount
2449       21444.71 EGP

In [257]:
# Convert 'transaction_amount' column from object to float 
def clean_transaction_amount(x):

    if isinstance(x, (int, float)) or pd.isna(x):
        return x

    return x.replace(' EGP', '').strip()

df['transaction_amount'] = df['transaction_amount'].apply(clean_transaction_amount).astype('float')
df['transaction_amount']

0        17829.01
1        16401.83
2         9678.29
3        19013.38
4        13834.95
           ...
9996      3552.90
9997     21559.69
9998      4181.33
9999     21443.71
10000    24974.25
Name: transaction_amount, Length: 10001, dtype: float64

In [258]:
# To drop duplicates

df = df.drop_duplicates()

# To reset index

df = df.reset_index(drop=True)

In [259]:
df.duplicated().sum()

np.int64(0)

In [260]:
# To drop missing values raws in 'device_risk_score' column --> very low Nan percentage

df.dropna(subset= 'device_risk_score', inplace= True, ignore_index= True)

In [261]:
df.isna().sum()

transaction_id                    0
transaction_amount                0
login_attempts                    0
device_risk_score                 0
transfer_frequency                0
anomaly_score                     0
account_age_days                  0
transaction_time_hour             0
failed_transactions_last_30d      0
avg_monthly_balance               0
daily_transaction_count           0
geo_distance_km                   0
session_duration_minutes          0
transaction_velocity_score        0
payment_channel                   0
authentication_type               0
card_present_flag                 0
international_transaction_flag    0
suspicious_ip_flag                0
fraud_flag                        0
dtype: int64

- In depth check for Numerical columns

In [262]:
# Generate descriptive statistics for numerical columns
df.describe()

,transaction_id,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,card_present_flag,international_transaction_flag,suspicious_ip_flag
count,9.968000e+03,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000,9968.000000
mean,1.005015e+06,12416.353378,6.442315,50.418529,39.650883,0.348810,2511.576445,11.555979,12.433287,249373.356396,60.621087,7601.849117,60.476023,50.110203,0.492576,0.498796,0.500702
std,2.880403e+03,7200.197743,3.453003,29.323253,23.412852,0.236841,1435.944497,6.963324,7.534700,144554.123735,34.825325,4330.143725,34.835030,29.248592,0.499970,0.500024,0.500025
min,1.000001e+06,6.270000,1.000000,0.000000,0.000000,0.010000,6.000000,0.000000,0.000000,104.160000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.002525e+06,6179.237500,3.000000,25.400000,19.000000,0.170000,1275.000000,6.000000,6.000000,122330.937500,30.750000,3894.750000,30.000000,24.800000,0.000000,0.000000,0.000000
50%,1.005016e+06,12328.775000,6.000000,50.300000,40.000000,0.310000,2513.000000,12.000000,13.000000,249829.525000,60.000000,7645.000000,61.000000,50.100000,0.000000,0.000000,1.000000
75%,1.007508e+06,18626.985000,9.000000,75.600000,60.000000,0.480000,3747.250000,18.000000,19.000000,373100.547500,91.000000,11371.500000,91.000000,75.400000,1.000000,1.000000,1.000000
max,1.010000e+06,24996.440000,12.000000,100.000000,80.000000,0.990000,5000.000000,23.000000,25.000000,499968.250000,120.000000,14997.000000,120.000000,100.000000,1.000000,1.000000,1.000000

In [263]:
# Select all numerical columns, then drop ID and flag columns that shouldn't be treated as regular numbers

num_cols = df.select_dtypes(include= 'number').columns.drop(
                                                            ['transaction_id', 'card_present_flag', 'international_transaction_flag',
                                                            'suspicious_ip_flag'])
num_cols

Index(['transaction_amount', 'login_attempts', 'device_risk_score',
       'transfer_frequency', 'anomaly_score', 'account_age_days',
       'transaction_time_hour', 'failed_transactions_last_30d',
       'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km',
       'session_duration_minutes', 'transaction_velocity_score'],
      dtype='object')

In [264]:
# Loop through each numerical column to create a histogram (distribution) and a box plot (outliers)
for col in num_cols:
    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

# Feature Engineering

- Create Account_Age_Group column from account_age_days column

In [265]:
# Define a function to categorize account age into groups, then apply it to create a new column
def account_groups(s):
    # If the account age is 30 days or less
    if s <= 30:
        return 'New Account'
    # If it's less than or equal to 365
    elif s <= 365:
        return 'Medium-term Account'
    # If it's greater than 365
    else:
        return 'Mature Account'
    

df['Account_Age_Group'] = df['account_age_days'].apply(account_groups)
df['Account_Age_Group']

0            Mature Account
1            Mature Account
2            Mature Account
3            Mature Account
4            Mature Account
               ...
9963         Mature Account
9964         Mature Account
9965    Medium-term Account
9966    Medium-term Account
9967         Mature Account
Name: Account_Age_Group, Length: 9968, dtype: object

In [266]:
df.head()

,transaction_id,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,...,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag,Account_Age_Group
0,1000001,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,...,3189,92,71.8,POS Terminal,OTP,1,1,1,False,Mature Account
1,1000002,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,...,839,63,11.8,Web Banking,Biometric,0,0,1,False,Mature Account
2,1000003,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,...,3938,80,35.7,ATM,OTP,1,0,1,False,Mature Account
3,1000004,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,...,11111,11,74.8,Mobile App,OTP,1,1,0,False,Mature Account
4,1000005,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,...,3171,87,0.0,Mobile App,OTP,1,0,0,False,Mature Account

- Create Amount_Category column from transaction_amount column

In [267]:
# Define a function to categorize transaction amounts into tiers, then apply it to the dataset

def trans_amount(x):
   
    if x < 50:
        return 'Micro'
    elif x < 200:
        return 'Low'
    elif x < 1000:
            return 'Medium'
    elif x < 5000:
            return 'High'
    else:
        return 'Very High'
    

df['Amount_Category'] = df['transaction_amount'].apply(trans_amount)
df['Amount_Category']

0       Very High
1       Very High
2       Very High
3       Very High
4       Very High
          ...
9963         High
9964    Very High
9965         High
9966    Very High
9967    Very High
Name: Amount_Category, Length: 9968, dtype: object

In [268]:
df.head()

,transaction_id,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,...,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag,Account_Age_Group,Amount_Category
0,1000001,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,...,92,71.8,POS Terminal,OTP,1,1,1,False,Mature Account,Very High
1,1000002,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,...,63,11.8,Web Banking,Biometric,0,0,1,False,Mature Account,Very High
2,1000003,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,...,80,35.7,ATM,OTP,1,0,1,False,Mature Account,Very High
3,1000004,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,...,11,74.8,Mobile App,OTP,1,1,0,False,Mature Account,Very High
4,1000005,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,...,87,0.0,Mobile App,OTP,1,0,0,False,Mature Account,Very High

# Data Analysis

### - What is the strongest indicator of fraud in the dataset?

In [269]:
# Calculate correlation matrix for numeric columns, extract correlation with 'fraud_flag', and sort it in descending order
df_corr = df.corr(numeric_only=True)['fraud_flag'].sort_values(ascending=False).reset_index()
df_corr.columns = ['Feature', 'Correlation_Score']
df_corr

                           Feature  Correlation_Score
0                       fraud_flag           1.000000
1                    anomaly_score           0.674461
2       transaction_velocity_score           0.009560
3               suspicious_ip_flag           0.009483
4         session_duration_minutes           0.005160
5               transaction_amount           0.004846
6                card_present_flag           0.000451
7            transaction_time_hour           0.000209
8                device_risk_score          -0.000238
9                   login_attempts          -0.000324
10             avg_monthly_balance          -0.001000
11              transfer_frequency          -0.002065
12                  transaction_id          -0.003725
13                account_age_days          -0.004560
14  international_transaction_flag          -0.004856
15    failed_transactions_last_30d          -0.007227
16         daily_transaction_count          -0.010145
17                 geo_distance_km          -0.017408

In [270]:
# To check how the device_risk_score is not in strong correlation with fraud_flag
risk_fraud_check_1 = (
    df.groupby('device_risk_score')['fraud_flag'].mean() * 100
)
print(risk_fraud_check_1)

device_risk_score
0.0      10.958904
0.1       0.000000
0.2       0.000000
0.3      16.666667
0.4      66.666667
           ...
99.6      0.000000
99.7      0.000000
99.8     14.285714
99.9     16.666667
100.0    11.481481
Name: fraud_flag, Length: 1001, dtype: float64

In [271]:
# compared with the correlation of anomaly_score with fraud_flag
risk_fraud_check = (
    df.groupby('anomaly_score')['fraud_flag'].mean() * 100
)
print(risk_fraud_check)

anomaly_score
0.01      0.000000
0.02      0.000000
0.03      0.000000
0.04      0.000000
0.05      0.000000
           ...
0.95    100.000000
0.96    100.000000
0.97     88.235294
0.98    100.000000
0.99     95.959596
Name: fraud_flag, Length: 99, dtype: float64

In [272]:
# Create an interactive horizontal bar chart to visualize feature correlation with the fraud flag
fig = px.bar(
    df_corr,
    x='Correlation_Score',
    y='Feature',
    orientation="h", 
    title="Correlation of Features with Fraud Flag",
    text_auto=".3f",
    )

fig.update_layout(yaxis={"categoryorder": "total ascending"})
fig.show()

In [273]:
# Create a vertical bar chart to visualize the correlation score of each feature with the fraud flag
fig = px.bar(
    df_corr,
    x='Feature',
    y='Correlation_Score', 
    title="Correlation of Features with Fraud Flag",
    text_auto=".3f",
    )

fig.show()

In [274]:
# Create a full correlation matrix rounded to 2 decimals, and drop the 'transaction_id' column from both rows and columns
df_corr_all = df.corr(numeric_only= True).round(2)
df_corr_all = df_corr_all.drop(
    index= 'transaction_id', columns= 'transaction_id'
)
df_corr_all

,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag
transaction_amount,1.00,-0.00,0.01,-0.01,-0.00,-0.01,-0.02,-0.00,-0.02,-0.00,0.00,-0.01,0.01,-0.01,-0.00,-0.00,0.00
login_attempts,-0.00,1.00,-0.02,-0.02,0.00,0.00,-0.00,0.01,0.01,0.01,0.01,-0.01,-0.00,-0.00,0.00,-0.01,-0.00
device_risk_score,0.01,-0.02,1.00,0.01,0.01,-0.01,-0.01,0.00,0.01,0.01,0.00,0.00,-0.00,0.00,-0.01,-0.00,-0.00
transfer_frequency,-0.01,-0.02,0.01,1.00,-0.00,0.01,0.02,-0.00,0.01,-0.01,0.00,-0.01,0.00,0.01,-0.02,0.01,-0.00
anomaly_score,-0.00,0.00,0.01,-0.00,1.00,-0.01,-0.01,0.02,-0.01,-0.00,-0.01,-0.00,0.01,-0.00,0.00,0.01,0.67
account_age_days,-0.01,0.00,-0.01,0.01,-0.01,1.00,0.00,0.01,-0.00,0.02,-0.01,0.01,-0.01,-0.00,-0.01,-0.01,-0.00
transaction_time_hour,-0.02,-0.00,-0.01,0.02,-0.01,0.00,1.00,0.00,-0.00,0.00,-0.00,-0.01,0.00,0.00,-0.00,0.02,0.00
failed_transactions_last_30d,-0.00,0.01,0.00,-0.00,0.02,0.01,0.00,1.00,-0.00,0.01,0.01,-0.02,-0.00,0.01,-0.01,-0.01,-0.01
avg_monthly_balance,-0.02,0.01,0.01,0.01,-0.01,-0.00,-0.00,-0.00,1.00,-0.00,0.01,0.01,0.01,-0.00,-0.00,-0.02,-0.00
daily_transaction_count,-0.00,0.01,0.01,-0.01,-0.00,0.02,0.00,0.01,-0.00,1.00,-0.01,-0.00,0.01,0.00,0.00,0.01,-0.01
geo_distance_km,0.00,0.01,0.00,0.00,-0.01,-0.01,-0.00,0.01,0.01,-0.01,1.00,-0.02,-0.01,-0.00,0.00,-0.00,-0.02
session_duration_minutes,-0.01,-0.01,0.00,-0.01,-0.00,0.01,-0.01,-0.02,0.01,-0.00,-0.02,1.00,-0.01,-0.02,-0.01,0.01,0.01
transaction_velocity_score,0.01,-0.00,-0.00,0.00,0.01,-0.01,0.00,-0.00,0.01,0.01,-0.01,-0.01,1.00,0.01,0.01,-0.00,0.01
card_present_flag,-0.01,-0.00,0.00,0.01,-0.00,-0.00,0.00,0.01,-0.00,0.00,-0.00,-0.02,0.01,1.00,0.00,-0.01,0.00
international_transaction_flag,-0.00,0.00,-0.01,-0.02,0.00,-0.01,-0.00,-0.01,-0.00,0.00,0.00,-0.01,0.01,0.00,1.00,-0.01,-0.00
suspicious_ip_flag,-0.00,-0.01,-0.00,0.01,0.01,-0.01,0.02,-0.01,-0.02,0.01,-0.00,0.01,-0.00,-0.01,-0.01,1.00,0.01
fraud_flag,0.00,-0.00,-0.00,-0.00,0.67,-0.00,0.00,-0.01,-0.00,-0.01,-0.02,0.01,0.01,0.00,-0.00,0.01,1.00

In [275]:
# Create an interactive heatmap to visualize the full correlation matrix with color coding
fig = px.imshow(df_corr_all, text_auto= True, 
    aspect="auto", 
    color_continuous_scale="Viridis", 
)

fig.update_layout(
    width=800,
    height=700,
    xaxis_tickangle=-45,  
)

fig.show()

### - How do total transaction volumes and fraud counts vary across different payment channel?

In [276]:
# Calculate the total number of transactions and the sum of fraud cases per payment channel 
fraud_by_channel = (
    df.groupby('payment_channel')['fraud_flag'].agg(['count', 'sum']).reset_index()
)
fraud_by_channel.columns = [
    'Payment_Channel',
    'Total_Transactions',
    'Fraud_Count',
]

fraud_by_channel = fraud_by_channel.sort_values(
    by="Fraud_Count", ascending = False
).reset_index(drop=True)

fraud_by_channel

  Payment_Channel  Total_Transactions  Fraud_Count
0      Mobile App                4791          615
1     Web Banking                3235          396
2    POS Terminal                1169          134
3             ATM                 773          100

In [277]:
# Create a bar chart to visualize the count of fraud cases across different payment channels
fig = px.bar(
    fraud_by_channel,
    x="Payment_Channel",
    y="Fraud_Count",
    title="Fraud Count by Payment Channel",
    text_auto=True,
    color="Payment_Channel",    
)

fig.update_layout(
    xaxis_title="The Payment Channel",  
    yaxis_title="Number of The Transactions")
fig.show()

### - Which Payment Channel exhibit the highest relative fraud rates?

In [278]:
# calcualte the fraud_percentage to the Total_Transactions by_channel
fraud_by_channel["Fraud_Percentage"] = (
    (fraud_by_channel["Fraud_Count"] / fraud_by_channel["Total_Transactions"]
) * 100 ).round(2)

fraud_by_channel = fraud_by_channel.sort_values(
    by="Fraud_Percentage", ascending=False
).reset_index(drop=True)

fraud_by_channel

  Payment_Channel  Total_Transactions  Fraud_Count  Fraud_Percentage
0             ATM                 773          100             12.94
1      Mobile App                4791          615             12.84
2     Web Banking                3235          396             12.24
3    POS Terminal                1169          134             11.46

In [279]:
# Create a grouped bar chart to visualize both metrics together along with the fraud percentage on hover
fig = px.bar(
    fraud_by_channel,
    x="Payment_Channel",
    y=["Total_Transactions", "Fraud_Count"],
    barmode="group",
    title="Total Transactions vs. Fraud Count per Payment Channel (with % Rate)",
    text_auto=True, 
    hover_data=["Fraud_Percentage"],
    labels={
        "variable": "Metric Type"
    }, 
)

fig.update_layout(
    xaxis_title="The Payment Channel",  
    yaxis_title="Number of The Transactions")

fig.show()

In [280]:
# Create a pie chart to visualize the percentage and distribution of fraud cases across payment channels
fig_pie = px.pie(
    fraud_by_channel,
    names="Payment_Channel",
    values="Fraud_Count", 
    title="Fraud Distribution by Payment Channel",
    hover_data=["Total_Transactions"
                ,"Fraud_Percentage"],
)

fig_pie.update_traces(textposition="inside", textinfo="percent+label")

fig_pie.show()

### - Which authentication type handles the highest volume of transactions and experiences the highest number of fraudulent activities?

In [281]:
# Calculate the total number of transactions and the sum of fraud cases per authentication_type
fraud_by_authentication_type = (
    df.groupby('authentication_type')['fraud_flag'].agg(['count', 'sum']).reset_index()
)
fraud_by_authentication_type.columns = [
    'authentication_type',
    'Total_Transactions',
    'Fraud_Count',
]

fraud_by_authentication_type = fraud_by_authentication_type.sort_values(
    by="Fraud_Count", ascending = False
).reset_index(drop=True)

fraud_by_authentication_type

         authentication_type  Total_Transactions  Fraud_Count
0                        OTP                4197          547
1  Two-Factor Authentication                2380          277
2              Password Only                1811          231
3                  Biometric                1580          190

In [282]:
# Create a bar chart to visualize the count of fraud cases by authentication type, using a red color scale
fig_2 = px.bar(
    fraud_by_authentication_type,
    x="authentication_type",
    y="Fraud_Count",
    title="Fraud Count by authentication_type",
    text_auto=True,
    color="Fraud_Count",  
    color_continuous_scale="Reds"
    
)
fig_2.show()

### - What is the ranking of authentication types based on their fraud percentage rate, sorted from highest to lowest risk?

In [283]:
# calcualte the fraud_percentage to the Total_Transactions by authentication_type
fraud_by_authentication_type = (
    df.groupby('authentication_type')['fraud_flag'].agg(['count', 'sum', 'mean']).reset_index()
)
fraud_by_authentication_type.columns = [
    'authentication_type',
    'Total_Transactions',
    'Fraud_Count',
    'Fraud_Percentage',
]
fraud_by_authentication_type['Fraud_Percentage'] = (fraud_by_authentication_type['Fraud_Percentage'] * 100).round(2)
fraud_by_authentication_type = fraud_by_authentication_type.sort_values(
    by='Fraud_Percentage', ascending = False
).reset_index(drop=True)


fraud_by_authentication_type

,authentication_type,Total_Transactions,Fraud_Count,Fraud_Percentage
0,OTP,4197,547,13.03
1,Password Only,1811,231,12.76
2,Biometric,1580,190,12.03
3,Two-Factor Authentication,2380,277,11.64

In [284]:
# Create a grouped bar chart to compare total transactions vs. fraud count per authentication type with custom colors
fig = px.bar(
    fraud_by_authentication_type,
    x="authentication_type",
    y=["Total_Transactions", "Fraud_Count"],
    barmode="group",
    title="Total Transactions vs. Fraud Count per authentication type (with % Rate)",
    text_auto=True, 
    hover_data=["Fraud_Percentage"],
    color_discrete_sequence=[
        "#2b5c8f",
        "#e67e22",
    ],
    labels={
        "variable": "Metric Type"
    }, 
)

fig.update_layout(
    xaxis_title="The Authentication Type",  
    yaxis_title="Number of The Transactions")

fig.show()

In [285]:
# Create a donut chart to visualize the distribution and percentage of fraud cases across different authentication types
fig_pie_2 = px.pie(
    fraud_by_authentication_type,
    names="authentication_type",
    values="Fraud_Count", 
    title="Fraud Distribution by Authentication Type",
    hover_data=["Total_Transactions"
                ,"Fraud_Percentage"],
    hole= 0.5,
)

fig_pie_2.update_traces(textposition="inside", textinfo="percent+label")

fig_pie_2.show()

### - What is the relationship between account age categories and fraud occurrences, and which group exhibits the highest risk?

In [286]:
# Group data by account age groups to calculate total transactions and fraud count, then sort in descending order
fraud_by_Account_Age_Group = (
    df.groupby('Account_Age_Group')['fraud_flag'].agg(['count', 'sum']).reset_index()
)
fraud_by_Account_Age_Group.columns = [
    'Account_Age_Group',
    'Total_Transactions',
    'Fraud_Count',
]

fraud_by_Account_Age_Group = fraud_by_Account_Age_Group.sort_values(
    by="Fraud_Count", ascending = False
).reset_index(drop=True)

fraud_by_Account_Age_Group

     Account_Age_Group  Total_Transactions  Fraud_Count
0       Mature Account                9264         1168
1  Medium-term Account                 663           72
2          New Account                  41            5

In [287]:
# Create a bar chart to visualize fraud count across different account age groups with custom colors
fig_3 = px.bar(
    fraud_by_Account_Age_Group,
    x="Account_Age_Group",
    y="Fraud_Count",
    title="Fraud Count by Account_Age_Group",
    text_auto=True,
    color="Account_Age_Group",
    color_discrete_sequence=[
           "#9A260F",
           "#e9701a",
           "#ebd613",

       ],
)

fig_3.update_layout(
    xaxis_title="Account Age Group",  
    yaxis_title="Fraud Count Transactions"
),
fig_3.show()

In [288]:
# Group data by account age group, calculate count, sum, and mean, convert to percentage, and sort descending
fraud_by_Account_Age_Group = (
    df.groupby('Account_Age_Group')['fraud_flag'].agg(['count', 'sum', 'mean']).reset_index()
)
fraud_by_Account_Age_Group.columns = [
    'Account_Age_Group',
    'Total_Transactions',
    'Fraud_Count',
    'Fraud_Percentage',
]
fraud_by_Account_Age_Group['Fraud_Percentage'] = (fraud_by_Account_Age_Group['Fraud_Percentage'] * 100).round(2)
fraud_by_Account_Age_Group = fraud_by_Account_Age_Group.sort_values(
    by='Fraud_Percentage', ascending = False
).reset_index(drop=True)

fraud_by_Account_Age_Group

     Account_Age_Group  Total_Transactions  Fraud_Count  Fraud_Percentage
0       Mature Account                9264         1168             12.61
1          New Account                  41            5             12.20
2  Medium-term Account                 663           72             10.86

In [289]:
# Create a grouped bar chart to compare total transactions vs. fraud count for each account age group
fig = px.bar(
    fraud_by_Account_Age_Group,
    x="Account_Age_Group",
    y=["Total_Transactions", "Fraud_Count"],
    barmode="group",
    text_auto= True, 
    title="Total Transactions vs. Fraud Count per Account Age Group",
    hover_data= "Fraud_Percentage",
    labels={
        "variable": "Metric Type"
    }, 
)

fig.update_layout(
    xaxis_title="Account Age Group",  
    yaxis_title="Count of The Transactions")

fig.show()

### - Is there a relationship between transaction_time_hour and fraud_flag? Specifically, which hours of the day experience the highest rate of fraudulent transactions?

In [290]:
# Calculate the percentage of fraud cases for each hour of the day and sort them in descending order
fraud_rate_by_hour = (
    (df.groupby("transaction_time_hour")["fraud_flag"].mean()* 100).sort_values(ascending =False)
).reset_index().round(2)


fraud_rate_by_hour

    transaction_time_hour  fraud_flag
0                       4       15.05
1                       9       14.50
2                      18       14.42
3                      22       14.12
4                      13       13.87
5                      21       13.46
6                       0       13.19
7                      12       13.16
8                       5       13.11
9                      19       13.03
10                      2       12.84
11                     14       12.77
12                     10       12.50
13                     17       12.03
14                     11       12.02
15                      8       12.01
16                      3       11.94
17                     16       11.88
18                     23       11.72
19                     15       11.28
20                      1       11.22
21                      7       10.51
22                      6       10.46
23                     20        9.15

In [291]:
# Sort fraud rate data chronologically by hour and create an interactive line chart with markers to show the hourly fraud trend
df_sorted = fraud_rate_by_hour.sort_values(
    by="transaction_time_hour", ascending=True
)
# Create an interactive line chart to visualize the fraud rate trend by the hour of the day with markers and text labels
fig = px.line(
    data_frame= df_sorted,
    x="transaction_time_hour",
    y="fraud_flag",
    markers=True, 
    title="Fraud Rate Trend by Hour of Day",
    text="fraud_flag",
)


fig.update_traces(
    textposition="bottom right", line=dict(color="#d9534f", width=2)
)

fig.update_layout(
    xaxis_title="Transaction Time Per Hour",  
    yaxis_title="Fraud Rate (%)",
)
fig.show()

### - Is there a specific transaction amount threshold where the fraud rate spikes significantly?

In [292]:
# Group data by transaction amount category, calculate total transactions and fraud count using named aggregation, and sort descending
fraud_rate_by_Amount_Category = (
    df.groupby('Amount_Category')['fraud_flag'].agg(Total_Transactions="count", Fraud_Count="sum").reset_index()
)

fraud_rate_by_Amount_Category = fraud_rate_by_Amount_Category.sort_values(
    by="Fraud_Count", ascending = False
).reset_index(drop=True)

fraud_rate_by_Amount_Category

  Amount_Category  Total_Transactions  Fraud_Count
0       Very High                7970          995
1            High                1591          198
2          Medium                 336           46
3             Low                  60            4
4           Micro                  11            2

In [293]:
# Create a bar chart to visualize fraud count distribution by transaction amount category with a red color scale
fig_bar = px.bar(
    fraud_rate_by_Amount_Category,
    x="Amount_Category",
    y="Fraud_Count",
    title="Fraud Distribution by Amount of The Transaction Category",
    text_auto=True,
    color="Fraud_Count", 
    hover_data=["Total_Transactions"],
    color_continuous_scale="Reds",
)

fig_bar.update_layout(
    xaxis_title="Amount of The Transaction Category",  
    yaxis_title="Fraud Count Transactions"
),
fig_bar.show()

In [294]:
# Group data by amount category, calculate total transactions, fraud count, and precise fraud rate percentage using custom lambda aggregation
fraud_rate_by_Amount_Category = (
    df.groupby('Amount_Category')['fraud_flag'].agg(Total_Transactions="count",
                                                     Fraud_Count="sum",
                                                        Fraud_Rate= lambda x: (x.mean() * 100).round(2)).reset_index()
)

fraud_rate_by_Amount_Category = fraud_rate_by_Amount_Category.sort_values(
    by="Fraud_Rate", ascending = False
).reset_index(drop=True)

fraud_rate_by_Amount_Category

  Amount_Category  Total_Transactions  Fraud_Count  Fraud_Rate
0           Micro                  11            2       18.18
1          Medium                 336           46       13.69
2       Very High                7970          995       12.48
3            High                1591          198       12.45
4             Low                  60            4        6.67

In [295]:
# Create an interactive bubble chart to analyze fraud rate by amount category, using bubble size for total transactions and color for fraud rate intensity
fig_scatter = px.scatter(
    fraud_rate_by_Amount_Category,
    x="Amount_Category",
    y="Fraud_Rate",
    size="Total_Transactions", # Bubble size represents the total volume of transactions
    color="Fraud_Rate",  # Color gradient based on the fraud rate percentage
    color_continuous_scale="Reds",
    hover_data=["Fraud_Count"],
    title="Fraud Rate by Amount Category (Bubble Chart)",
    text="Fraud_Rate",
)

fig_scatter.update_traces(
    textposition="top center"
)
fig_scatter.update_layout(
    xaxis_title="Transaction Amount Category",  
    yaxis_title="Fraud Rate (%)",
)
fig_scatter.show()

# Save Cleaned Dataframe

In [296]:
df.to_csv('Cleaned_Data_Fraud_Trans.csv', index= False)

In [297]:
df.to_parquet('Cleaned_Data_Fraud_Trans.parquet')